### ISSUE TITLE
Network Manager unmanaged interface causes packagekit to conclude its off-line incorrectly

### ISSUE THREAD

**Issue by davehill734455** [hughsie/PackageKit#336]
When trying to update the cache, it seems that PackageKit looks to NetworkManager for online status. If NetworkManager is not managing any  network interfaces (nmcli d), PackageKit concludes its off-line. However, the interface may be up and connected using traditional networking tools. 

Disabling NetWorkManager is said to fix the problem, e.g. https://github.com/cockpit-project/cockpit/issues/8477: 
sudo systemctl disable NetworkManager.service
and that works on my machine. 

Mine is a Xen host, so I need finer control of the network interface than is available in NetworkManager, so I don't use it. Disabling it was fine for my needs at least. It would be helpful if PK could do a more thorough check for networkig, though, so disabling Network Manager is not required. (Bug originally filed on KDE bug tracker because this behaviour caused problems for Apper and Discover:https: //bugs.kde.org/show_bug.cgi?id=407807)

**Comment by hughsie** [comment]
If you have NetworkManager installed, we expect it to be configured and working. I think PK is doing exactly what it should do here, sorry.

**Comment by davehill734455** [comment]
I ask you to reconsider. NetworkManager is installed, configured and working properly. It specifically provides for unmanaged interfaces with an option in /etc/NetworkManager/NetworkManager.conf:
[ifupdown] 
managed=false
(See, e.g., https://wiki.debian.org/NetworkManager#doc)

NM then leaves the interface alone, to be managed manually. Thus, NM is working as designed and the interface is up, but PK is reporting to the user that the system is off-line. It seems to me that PK is making an invalid assumption about NM - if it's running, it's responsible for connectivity.  

Why would anyone do this? In my case, it lets me switch the interface easily between unmanaged Xen bridge configuration and a "normal" configuration. I'm the third on the KDE bug report (above)  since May 2019 - two others have reported the same issue. Nor is it limited to KDE:  https://github.com/cockpit-project/cockpit/issues/8477.   It's a bit challenging to troubleshoot because the front-ends like Apper and Discover parrot the off-line message but don't mention PK or NM.  It's hard to see how they could address the problem other than perhaps more detailed error messages.

**Comment by hughsie** [comment]
> if it's running, it's responsible for connectivity

Is there anything on the D-Bus interface that tells us to ignore NM? If you work out the library calls we need to do and open a PR I guess we can re-open this.

**Comment by deadlydud** [comment]
my 2-cent opinion:   
if NM check says offline, then try fsock connect to remote, small 3-sec timeout, 
if connected, ignore NM and continue as connected.

**Comment by davehill734455** [comment]
I'll leave it to the developer to respond to your idea, but would add a 
few notes.

I looked over the code. As i read it, PK checks with GNetworkMonitor in 
glib/gio not by PK to Network Manager, so the false negative does not 
arise here but upstream. I've been meaning to take it up there, just 
haven't gotten around to it. It's also a bit daunting to go scratching 
around in something so fundamental (as it was here).

The problem seems to be more common than one might expect. Searching for 
the reported error, "cannot refresh cache whilst offline", returns bug 
reports from several clients of packageKit. ("Whilst" is  is less common 
outside of the UK. It helps narrow the search results.)

**Comment by HRogge** [comment]
I have exactly the same problem... I am using NetworkManager for Wifi, but systemd-networkd for Ethernet... PackageKit constantly thinks I am offline when using no Wifi.

A configuration option for "not NM interfaces" would be perfect... if any of them has an outgoing default route, it should be okay to assume "I am online".

**Comment by hughsie** [comment]
> I am using NetworkManager for Wifi, but systemd-networkd for Ethernet...

I think that's somewhat unusual...

> A configuration option

I don't think that's in the spirit of "just works", sorry.

**Comment by HRogge** [comment]
> > I am using NetworkManager for Wifi, but systemd-networkd for Ethernet...
> I think that's somewhat unusual...

My Ethernet configuration is a little bit more complicated... NetworkManager is not an useful too for this. But when I am on a business trip I need easy access to Wifi (or even LTE)... where it makes perfectly sense to have Network Manager.

> > A configuration option
> I don't think that's in the spirit of "just works", sorry.

At the moment the state is neither "just works" or "works with some effort" but "just does not work".

Even an option like "ignore Network Manager, just assume you are online" like you find it in Pidgin (-f, --force-online: Try to be online even if the network is reported (by Windows, or NetworkManager on Linux) to be unavailable) would be better than the current state for more complex situations.

**Comment by davehill734455** [comment]
I raised this bug but now see that the problem is not with packagekit. 
PK does not check Network Manager directly. PK's code calls 
GNetworkMonitor (in pk-backend.c) which is part of Red Hat's glib/gio 
library. Thus, the false negative (network not available when it 
actually is) is not caused by PK but upstream in glib/gio (or 
conceivably upstream of that).

It's understandable that the bug gets traced to packagekit. It comes up 
again and again in applications from various distributions that use 
packagekit as a backend interface. However, this is not a bug in 
packagekit code and I can understand Mr. Hughes's reluctance to code 
around it.

I've been digging through the gio code 
(https://github.com/GNOME/glib/blob/master/gio/tests/network-monitor.c) 
to try to figured out why it gets it wrong but haven't got there yet. 
(My C and networking skills are pretty rudimentary.) Meanwhile, the 
command line package manager for each individual distribution (apt in my 
case) is only slightly more annoying to use.

**Comment by eeickmeyer** [comment]
Sorry to necro-bump this, but it appears to be a race condition where packagekitd is initializing prior to the network being online and causing packagekitd to forever think it's offline. Was easily fixed via a patch to `packagekit.service.in`.
See the attached patch.

[10-wait-network-online.patch.txt](https://github.com/PackageKit/PackageKit/files/7140300/10-wait-network-online.patch.txt)

**Comment by hughsie** [comment]
@eeickmeyer that seems sane -- do you mind opening a Pull Request with that patch included please? Thanks.

**Comment by tristangrimaux** [comment]
This problem persists in march 2023. Packagekit is a tool to unify and make the administration of packages and updates consistent across many distros in Linux, and the fact that the option "UseNetworkManager=false" is ignored by PackageKit is clearly a bug.

**Comment by davehill734455** [comment]
To make matters worse, PK is inconsistent. It triggers user-facing packing apps (Discover, Apper, etc) to display, "updates available" messages but then won't carry them out.

**Comment by tristangrimaux** [comment]
The availability of the network should be handled by the corresponding backend, it's not the job of PackageKit

> To make matters worse, PK is inconsistent. It triggers user-facing packing apps (Discover, Apper, etc) to display, "updates available" messages but then won't carry them out.
