### ISSUE TITLE
DNF backend doesn't apply all variable substitutions.

### ISSUE THREAD

**Issue by jcpunk** [hughsie/PackageKit#339]
PackageKit isn't correctly reading in all the vars from /etc/dnf/vars/  (and /etc/yum/vars/)

Replication steps:
1. create a repo with a number of local vars (see CentOS 8 Stream)
2. pkcon refresh

Results:
```
Fatal error: cannot update repo 'Stream-AppStream': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Status code: 404 for http://mirror.centos.org/$contentdir/$stream/AppStream/x86_64/os/repodata/repomd.xml
```

Expected results:

The vars should be replaced as normal via dnf.

Additional Info:

In theory it really should be doing whatever the C equivalent is of https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/payload/dnfpayload.py#L332

**Comment by jcpunk** [comment]
All upstream bits are fixed, PackageKit now works as expected.

**Comment by Mikaela** [comment]
I think this is still happening in PackageKit 1.2.2 on Fedora 33 with `$releasever` either in repository name or baseurl or `gpgkey`.

I am getting `Fatal error: repodata proton-fedora-$releasever-unstable was not complete: repomd.xml GPG signature verification failed: Bad GPG signature` when I `pkcon refresh` and I see the same error upon logging in to KDE Plasma, while `dnf` works as expected (calls the repository as `proton-fedora-33-unstable` and has no GPG verification errors).

I think this comes from my `/etc/yum.repos.d/protonvpn-unstable.repo`

```
[proton-fedora-$releasever-unstable]
name="fedora-$releasever-unstable"
baseurl=https://repo.protonvpn.com/fedora-$releasever-unstable/
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://repo.protonvpn.com/fedora-$releasever-unstable/public_key.asc
```
